### ISSUE TITLE
Not actually an issue!

### ISSUE THREAD

**Issue by deathbybandaid** [chadmayfield/pihole-blocklists#1]
Hi, I occasionally skim through github for interesting pihole tweaks/projects.

Yours is definitely one that peaked my interest.

I have been working on a script to install other projects.

https://github.com/deathbybandaid/piadvanced

I don't want to steal anybodies work, and I try my hardest to make sure I give credit to the correct people.

I plan on keeping an eye on your project.

I didn't know how else to contact you, so feel free to close this when you see it.

**Comment by chadmayfield** [comment]
Great! Thanks for checking it out.  I checked out your repo and it's impressive.  For right now for this project I just envision creating custom blocklists, automatically running the update from cron, and automatically installing them so I don't have to.  If you like it I'd love you to contribute once I get more code thrown together.

If you'd like to contact me about the project you can see several methods on my profile page (by visiting https://keybase.io/crm or @chadrmayfield on twitter).
