### ISSUE TITLE
Non-porn domains blocked

### ISSUE THREAD

**Issue by KnightTim** [chadmayfield/pihole-blocklists#11]
I use both your lists with my pihole and noticed it was blocking a number of non-porn sites.  

I was looking for something cute for my wife and noticed that Victoria Secret is blocked, it sells lingerie/underwear, it's not porn. Though, I can understand why some people would it blocked, as it can have provocative images. This got me curious, so with the help of google, I have a list of lingerie/underwear type sites that your list is blocking. My list is likely incomplete. 

If you don't want to unblock them that is fine with me just close the issue, but I figured you should know. 

`victoriasecret.com`
`www.victoriasecret.com `
`fredericks.com`
`www.fredericks.com`
`barenecessities.com`
`www.barenecessities.com`
`yandy.com`
`www.yandy.com`
`lingeriediva.com`
`www.lingeriediva.com`
`lasenza.com`
`www.lasenza.com`
`amiclubwear.com`
`www.amiclubwear.com`
`forplaycatalog.com`
`www.forplaycatalog.com`
`spicylingerie.com`
`www.spicylingerie.com`
`dear-lover.com`
`www.dear-lover.com`
`hipsandcurves.com`
`www.hipsandcurves.com`
`smartandsexy.com`
`www.smartandsexy.com`
`herroom.com`
`www.herroom.com`
`petitecherry.com`
`www.petitecherry.com`
`torrid.com`
`www.torrid.com`

This one is a magazine, I'm pretty sure it isn't even adult focused 
( https://en.wikipedia.org/wiki/Refinery29 )
`refinery29.com`
`www.refinery29.com`

**Comment by chadmayfield** [comment]
I agree, based on [legal definitions](http://www.duhaime.org/LegalDictionary/P/Pornography.aspx) of pornography these sites don't apply (otherwise I'd have to block Amazon as well for selling lingerie);

> Pornography is the portrayal of erotic behavior designed to cause sexual excitement. It is words, acts, or representations that are calculated to stimulate sex feelings independent of the presence of another loved and chosen human being. It is divorced from reality in its sole purpose to stimulate erotic response. It is preoccupied with and concentrates on sex organs for the purpose of sexual stimulation. It emphasizes them and focuses on them in varying ways calculated to incite sexual desire.

As I've stated before, these sites are blocked upstream.  The best I can do is add them to the exclude list so they don't find themselves in my lists.  Thanks for taking the time to file a bug report.  I'll update the lists accordingly.
