### ISSUE TITLE
False Positive found

### ISSUE THREAD

**Issue by KnightTim** [chadmayfield/pihole-blocklists#12]
I have found a false positive. It's a news website. ( https://en.wikipedia.org/wiki/Heavy.com ) 

    heavy.com 

I assume this is due to your upstream sources, if you don't want me to report false positives I find please let me know and I'll just whitelist things on my side. 

Thanks so much for maintaining this list.

**Comment by chadmayfield** [comment]
@KnightTim opening issues for false positives is great, keep them coming if you find some.  I’m not able to take care of this right now, but I’ll definitely add it to the white list and regenerate the lists within the next couple of weeks. Feel free to add any other sites to this issue if you find any.

**Comment by KnightTim** [comment]
I found another site: 

`motherfuckingwebsite.com`

It's a joke website, I assume since it has the f-word in it the list picks it up.

**Comment by chadmayfield** [comment]
Thanks @KnightTim I’ll get that site added in the next couple of days as well.  I’ve been out of the country for a couple of weeks and I should be able to get to this soon.
