### ISSUE TITLE
yourbrainonporn.com - Probably false positive

### ISSUE THREAD

**Issue by drego85** [chadmayfield/pihole-blocklists#17]
I don't know exactly which site you want to block, only those with explicit content or event those that talk about porn in general.

But let me point out that the site yourbrainonporn.com site is in your blocklist. This scientific site talks about the effects of porn.

Maybe it should be removed, consider yourself.

**Comment by drego85** [comment]
Thanks @chadmayfield !

**Comment by chadmayfield** [comment]
Any time!  Let me know if any other domains need to be whitelisted.  (BTW, I'm a happy BackBox user!)
