### ISSUE TITLE
Doordash.com

### ISSUE THREAD

**Issue by lowlandghost** [chadmayfield/pihole-blocklists#7]
Hi,

I've been using your blocklists for a while and they're great! I just noticed that recently doordash.com was added to the blocklist. Doordash isn't porn, it's a food delivery service. I've added a whitelist on my Pi-hole for the time being but I'd figure I ask why/how it was blocked in the first place.

Thanks!

**Comment by chadmayfield** [comment]
@ambersnow Sorry about that and thanks for using them!  To create the lists I simply pull a few lists from a couple of upstream providers and create my blacklist.  If doordash.com was in the latest list it was a problem upstream.  Needless to say it shouldn't be and I need to fix that.  So I'll add a fix to my list generation that will whitelist known good sites, doordash.com being one.
