### ISSUE TITLE
Add Domains

### ISSUE THREAD

**Issue by w8Pk1y** [chadmayfield/pihole-blocklists#9]
Please add these domains to your Porn Block List:
anymad.com
bestindiansex.com
bestsouthindiansex.com
cdn.originalindianporn.com
cdn.xxindianporn.com
cdngangsta.com
crazydesisex.com
desifuckonline.com
desipapa.xxx
desipapa2.com
desipornfilm.com
desisex.tv
dirtypornphotos.com
extraindiansex.com
finaldesitube.com
freeindiansexscandals.com
freesexindians.com
fyredet.xyz
hardindianporn.com
homeindiansex.com
hotdesitube.com
hotindianporntube.com
hotnakedgirls.net
hyperspeed.pro
indian-sex-videos.net
indianfucklovers.com
indiangirlsclub.com
indianhamster.com
indiankinkygirls.com
indiansexchudai.com
indiansexphotos.com
indiansexvideos.porn
indiapornonline.com
mixindiansex.com
mostdesisex.com
netdna-ssl.com
newindianfuck.com
nicedesiporn.com
ohindiansex.com
onindiansex.com
ooodesi.com
originalindianporn.com
pepperindiaporn.com
prettyindiaporn.com
provocationstudio.ru
sexpussynude.com
sexyindiantube.com
sexzindian.com
soindianporn.com
soindianporn.com
th.cdngangsta.com
the-urbn.com
totaldesiporn.com
unseenmms.com
wellindianporn.com
wetindianporn.com
xbombo.com
xindiansex.com
xvideos-cdn.com
xxindianporn.com
xxxdesisexvideos.com
xxxindian.pro
ypncdn.com

**Comment by chadmayfield** [comment]
Sorry as of right now this is not a list that is taking additions.  I simply take upstream lists and compare them to the Alexa top one million site list.  Then create a list of the most visited porn sites to block.  

The goal of this project is to blacklist the most common porn sites out there.  Trying to keep up with sites that crop up is not something I'd like to do.  If you'd like you can fork the repository and make the changes yourself and use them... or you could add them to your own with a simple bash while loop like so;

https://gist.github.com/chadmayfield/3c2f47f949a1a51a05b5a7e00545533d

Perhaps in the future I'll extend it, but as for now I don't have the time.  Thanks.
